[libraries]
commons-codec = "commons-codec:commons-codec:1.15"
interop-common = "com.projectronin.interop:interop-common:2.0.1-SNAPSHOT"
interop-commonHttp = "com.projectronin.interop:interop-common-http:2.0.0"
interop-commonJackson = "com.projectronin.interop:interop-common-jackson:2.0.0"
interop-fhir = "com.projectronin.interop.fhir:interop-fhir:1.1.1-SNAPSHOT"
testcontainers-bom = "org.testcontainers:testcontainers-bom:1.17.3"
ktor-client-cio = "io.ktor:ktor-client-cio:2.0.2"
ktor-client-core = "io.ktor:ktor-client-core:2.0.2"
ktor-client-content-negotiation = "io.ktor:ktor-client-content-negotiation:2.0.2"
ktor-client-logging = "io.ktor:ktor-client-logging:2.0.2"
ktor-serialization-jackson = "io.ktor:ktor-serialization-jackson:2.0.2"
ktor-client-mock = "io.ktor:ktor-client-mock:2.0.2"
mockk = "io.mockk:mockk:1.12.4"
