[libraries]
azure-identity="com.azure:azure-identity:1.5.3"
azure-storage-blob="com.azure:azure-storage-blob:12.13.0"
commons-codec = "commons-codec:commons-codec:1.15"
interop-common = "com.projectronin.interop:interop-common:3.0.0"
interop-commonHttp = "com.projectronin.interop:interop-common-http:3.0.0"
interop-commonJackson = "com.projectronin.interop:interop-common-jackson:3.0.0"
interop-fhir = "com.projectronin.interop.fhir:interop-fhir:2.0.0-SNAPSHOT"
testcontainers-bom = "org.testcontainers:testcontainers-bom:1.17.3"
ktor-client-cio = "io.ktor:ktor-client-cio:2.0.3"
ktor-client-core = "io.ktor:ktor-client-core:2.0.3"
ktor-client-content-negotiation = "io.ktor:ktor-client-content-negotiation:2.0.3"
ktor-client-logging = "io.ktor:ktor-client-logging:2.0.3"
ktor-serialization-jackson = "io.ktor:ktor-serialization-jackson:2.0.3"
ktor-client-mock = "io.ktor:ktor-client-mock:2.0.3"
mockk = "io.mockk:mockk:1.12.7"
