[libraries]
commons-codec = "commons-codec:commons-codec:1.15"
dd-trace-api = "com.datadoghq:dd-trace-api:1.1.3"
interop-common = "com.projectronin.interop:interop-common:3.1.0"
interop-commonHttp = "com.projectronin.interop:interop-common-http:3.1.0"
interop-commonJackson = "com.projectronin.interop:interop-common-jackson:3.1.0"
interop-fhir = "com.projectronin.interop.fhir:interop-fhir:4.0.0"
ktor-client-mock = "io.ktor:ktor-client-mock:2.1.3"
mockk = "io.mockk:mockk:1.13.3"
mockserver-client-java = "org.mock-server:mockserver-client-java-no-dependencies:5.14.0"
oci-common = "com.oracle.oci.sdk:oci-java-sdk-common:3.0.1"
oci-objectstorage = "com.oracle.oci.sdk:oci-java-sdk-objectstorage:3.0.1"
oci-http-client = "com.oracle.oci.sdk:oci-java-sdk-common-httpclient-jersey3:3.0.1"
spring-boot-parent = "org.springframework.boot:spring-boot-parent:2.7.5"
testcontainers-bom = "org.testcontainers:testcontainers-bom:1.17.6"
