[libraries]
commons-codec = "commons-codec:commons-codec:1.15"
interop-common = "com.projectronin.interop:interop-common:3.1.0"
interop-commonHttp = "com.projectronin.interop:interop-common-http:3.1.0"
interop-commonJackson = "com.projectronin.interop:interop-common-jackson:3.1.0"
interop-fhir = "com.projectronin.interop.fhir:interop-fhir:3.1.1"
ktor-client-mock = "io.ktor:ktor-client-mock:2.1.2"
mockk = "io.mockk:mockk:1.13.2"
mockserver-client-java = "org.mock-server:mockserver-client-java-no-dependencies:5.14.0"
oci-common = "com.oracle.oci.sdk:oci-java-sdk-common:2.46.0"
oci-objectstorage = "com.oracle.oci.sdk:oci-java-sdk-objectstorage:2.46.0"
testcontainers-bom = "org.testcontainers:testcontainers-bom:1.17.5"
