[libraries]
commons-codec = "commons-codec:commons-codec:1.15"
dd-trace-api = "com.datadoghq:dd-trace-api:0.115.0"
interop-common = "com.projectronin.interop:interop-common:3.1.0"
interop-commonHttp = "com.projectronin.interop:interop-common-http:3.1.0"
interop-commonJackson = "com.projectronin.interop:interop-common-jackson:3.1.0"
interop-fhir = "com.projectronin.interop.fhir:interop-fhir:4.0.0-SNAPSHOT"
ktor-client-mock = "io.ktor:ktor-client-mock:2.1.3"
mockk = "io.mockk:mockk:1.13.2"
mockserver-client-java = "org.mock-server:mockserver-client-java-no-dependencies:5.14.0"
oci-common = "com.oracle.oci.sdk:oci-java-sdk-common:2.48.0"
oci-objectstorage = "com.oracle.oci.sdk:oci-java-sdk-objectstorage:2.48.0"
ronin-kafka = "com.projectronin:ronin-kafka:0.0.1-SNAPSHOT"
spring-boot-parent = "org.springframework.boot:spring-boot-parent:2.7.5"
testcontainers-bom = "org.testcontainers:testcontainers-bom:1.17.5"
