name: Interop Aidbox Integration Tests
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: self-hosted-azure
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Gradlew Integration Tests
        run: ./gradlew :interop-aidbox:it
        env:
          AIDBOX_LICENSE_ID: ${{ secrets.ORG_AIDBOX_LICENSE_ID }}
          AIDBOX_LICENSE_KEY: ${{ secrets.ORG_AIDBOX_LICENSE_KEY }}
