name: Interop Aidbox Integration Tests
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradlew Integration Tests
        run: ./gradlew :interop-aidbox:it
        env:
          PACKAGE_USER: ${{ secrets.PACKAGES_PAT_USER }}
          PACKAGE_TOKEN: ${{ secrets.PACKAGES_PAT }}
          AIDBOX_LICENSE_ID: ${{ secrets.ORG_AIDBOX_LICENSE_ID }}
          AIDBOX_LICENSE_KEY: ${{ secrets.ORG_AIDBOX_LICENSE_KEY }}
