name: Interop Aidbox Testcontainer Tests
on:
  push:
    branches: [ master ]

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradlew Test
        run: ./gradlew :interop-aidbox-testcontainer:test
        env:
          PACKAGE_USER: ${{ secrets.PACKAGES_PAT_USER }}
          PACKAGE_TOKEN: ${{ secrets.PACKAGES_PAT }}
          AIDBOX_LICENSE_ID: ${{ secrets.AIDBOX_LICENSE_ID }}
          AIDBOX_LICENSE_KEY: $${ secrets.AIDBOX_LICENSE_KEY }}

      - name: Upload Code Coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          file: ./interop-aidbox-testcontainer/codecov/test/jacocoTestReport.xml
          flags: aidbox-tc
